### ISSUE TITLE
Where would I connect a LiPo battery?

### ISSUE THREAD

**Issue by skybound** [joric/nrfmicro#10]
Thank you very much for this.  I ordered some PCBs myself, they should arrive within a few weeks.

I see there's a LiPo charger, but it doesn't look like VBAT is broken out to a pin.  How would I connect a battery?

**Comment by joric** [comment]
[https://github.com/joric/nrfmicro/wiki/Hardware](Li-Po battery uses RAW and GND pins)

**Comment by skybound** [comment]
I missed that section. Thank you.
