### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by Na-Cly** [joric/nrfmicro#12]
Hey I see your pcb uses the Unlicense, but do you know if there's any restrictions when building this in regards to reselling? I'm planning on making a small batch and wanted to know if there was anything you knew of that would restrict resale.

**Comment by joric** [comment]
It should be fine. Adafruit bootloader is MIT licensed so it should be ok to sell preflashed devices as well. But don't take my word for it, do your own research, I can't really help for that matter.
