### ISSUE TITLE
coin cell battery vs lipo

### ISSUE THREAD

**Issue by fi0** [joric/nrfmicro#13]
If I use a coin cell battery like CR2032 (not rechargeable) instead of lipo, how should I correctly connect it to the board? Thank you!

**Comment by joric** [comment]
I haven't really though that through ) Better buy a lipo cell or a chargeable LIR2032 they're cheap. You can connect it to RAW/GND but there are no solder jumpers to disconnect it from the charger. I think you can just desolder MCP73831 that feeds 4.2V to the battery so the battery won't explode and you will be good.

**Comment by fi0** [comment]
Thank you @joric, I'll go with your first advice :)
