### ISSUE TITLE
Question about jumpers

### ISSUE THREAD

**Issue by Na-Cly** [joric/nrfmicro#15]
Hey I noticed there's a few jumper pads. I can't seem to find on the wiki where it talks about what they are used for.

Thanks in advance.

**Comment by joric** [comment]
Promicros on corne are usually flipped, if you got corne with hotswap sockets you can use those jumpers to keep antenna up. top 4 rows of pins can be flipped by those jumpers, bottom 8 rows of pins could be just remapped, as here (build with CFLAGS += -DFLIPPED_NRFMICRO):
https://github.com/joric/qmk/blob/nrf52-jorne/keyboards/jorne_ble/board/custom_board.h
