### ISSUE TITLE
Pull USB-C pads farther down for handsoldering

### ISSUE THREAD

**Issue by skorokithakis** [joric/nrfmicro#16]
This board is great, but handsoldering the USB-C module is rather harder than it should be because the pads are sitting flush with the connector pins. If you pull the pads a bit farther down, there will be enough space to handsolder comfortably.

I only managed to do it when I cut the top throughholes a bit and pushed the connector higher up to give it some space.

**Comment by joric** [comment]
Yeah I'll account for it. The whole USB-C footprint needs rethinking because the front of the connector sits flush the pcb, it should be out for about 1mm. Haven't had so many problems with soldering though, just used more flux :)
