### ISSUE TITLE
Led polarity

### ISSUE THREAD

**Issue by Na-Cly** [joric/nrfmicro#17]
Is there an easy way to tell which way the LEDs lay for polarity? Its hard to tell from the picture, but I notice on the bottom I see a shape that looks like you can determine cathode from anonde.

**Comment by joric** [comment]
what the hell. it's a square bracket on the pcb and a green stripe on the led. it's a STANDARD smd led footprint nobody redraws that from scratch

**Comment by Na-Cly** [comment]
Never used smd LEDs this small and the hardware page shows the led already soldered. Thanks for getting back to me so quickly.
