### ISSUE TITLE
Converting to uf2, output size: 135168, start address: 0x26000

### ISSUE THREAD

**Issue by 624245305** [joric/nrfmicro#2]
Using the NRF52840 host, QMK's make command creates two files, master.hex and slave.hex, and converts the UF2 file with uf2conv.py, but the default is start address: 0x26000. Copying two UF2 files to Mass Storage is not fully operational, connecting the computer to display the USB composite device, the phone cannot search for Bluetooth, and nrf connect can be connected. The address of my two converted UF2 files cannot be 0x26000

**Comment by joric** [comment]
Why copy two files? It's either master or slave, not both.
