### ISSUE TITLE
Group Buy Plans

### ISSUE THREAD

**Issue by NellyWhadsDev** [joric/nrfmicro#20]
Heyo,

Wondering if you have any plans to run a group buy for this any time soon. Also, the build log is awesome - do you have something similar for ideas/planned changes/what still needs to be done (even if just for personal satisfaction)?

Awesome work; hoping to have these driving my first crkbd and/or ergodash boards.

**Comment by joric** [comment]
None. No plans. Regarding ideas, see midmount and devel branches, PCBs are yet untested (still waiting for them, turnarounds are like 2 months considering sourcing all the components and sometimes it gets lost in transit). I got rid of voltage regulator, there's an internal one, added power mosfet and a better battery divider (800K/2M) to minimize leaks but it costed a physical switch and reversability in favor of ultra low profile (~2.5mm if you remove shielding).
