### ISSUE TITLE
Lipo battery not charging

### ISSUE THREAD

**Issue by luantty2** [joric/nrfmicro#21]
The voltage of battery does not change after charging for 1 hour, my multimeter always says the voltage of battery is 3.90V, is there any way to detect if the battery charging circuit is working?
And I noticed that the voltage of my 'VBUS' is 5.16V, which is a little bit higher than the protection circuit on the battery(they specified 4.2V-5V), could this be the problem of preventing the battery from charging?

**Comment by joric** [comment]
Charging voltage is always 4.2V, VBUS is always 5V. Battery should charge no matter what, if the voltage is right.

**Comment by luantty2** [comment]
Okay, it's charging now, caused by my bad soldering, thanks.
