### ISSUE TITLE
Issue: Flashing Bootloader for Holyiot nrf52840 

### ISSUE THREAD

**Issue by marhalloweenvt** [joric/nrfmicro#23]
Hello joric,

I have followed your work for a while and they are really amazing.
Recently, i decided to design a board using nrf52840. So i bought some Holyiot nrf52840 module from China and followed your schematic. Currently, i am using stlink-v2 and Msys32 to flash this module. I can't unlock nor flash bootloader for this module. Please have look at below log for flashing bootloader:

> $ openocd -f interface/stlink.cfg -f target/nrf52.cfg -c "gdb_flash_program enable" -c "gdb_breakpoint_override hard" -c "init"
> Open On-Chip Debugger 0.10.0+dev-00870-gaf952850b (2019-05-22-11:05)
> Licensed under GNU GPL v2
> For bug reports, read
>         http://openocd.org/doc/doxygen/bugs.html
> Info : auto-selecting first available session transport "hla_swd". To override use 'transport select <transport>'.
> Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
> force hard breakpoints
> Info : clock speed 1000 kHz
> Info : STLINK V2J29S7 (API v2) VID:PID 0483:3748
> Info : Target voltage: 3.143445
> Info : nrf52.cpu: hardware has 6 breakpoints, 4 watchpoints
> Info : Listening on port 3333 for gdb connections
> Info : Listening on port 6666 for tcl connections
> Info : Listening on port 4444 for telnet connections
> Info : accepting 'telnet' connection on tcp/4444
> target halted due to debug-request, current mode: Thread
> xPSR: 0x01000000 pc: 0x00000a80 msp: 0x20000400
> invalid command name "mass_erase"
> invalid command name "mass_erase"
> wrong # args: should be "program filename ?arg...?"
> target halted due to debug-request, current mode: Thread
> xPSR: 0x01000000 pc: 0x00000a80 msp: 0x20000400
> ** Programming Started **
> Warn : Unknown device (HWID 0x0000015b)
> Info : Padding image section 0 at 0x00000b00 with 1280 bytes
> Info : Flash write discontinued at 0x00025de8, next section at 0x000f4000
> Warn : using fast async flash loader. This is currently supported
> Warn : only with ST-Link and CMSIS-DAP. If you have issues, add
> Warn : "set WORKAREASIZE 0" before sourcing nrf51.cfg/nrf52.cfg to disable it
> Warn : using fast async flash loader. This is currently supported
> Warn : only with ST-Link and CMSIS-DAP. If you have issues, add
> Warn : "set WORKAREASIZE 0" before sourcing nrf51.cfg/nrf52.cfg to disable it
> Warn : Adding extra erase range, 0x10001000 .. 0x10001013
> Error: The chip was not pre-programmed with SoftDevice stack and UICR cannot be erased separately. Please issue mass erase before trying to write to this region
> Error: failed erasing sectors 0 to 0
> embedded:startup.tcl:449: Error: ** Programming Failed **
> in procedure 'program'
> in procedure 'program_error' called at file "embedded:startup.tcl", line 508
> at file "embedded:startup.tcl", line 449
> shutdown command invoked
> Info : dropped 'telnet' connection

And when i tried to unlock this module, it gives me this mess:

> $ openocd -d2 -f interface/cmsis-dap.cfg -f target/nrf52.cfg -c "init" -c "nrf52.dap apreg 1 0x04 0x01"
> Open On-Chip Debugger 0.10.0+dev-00870-gaf952850b (2019-05-22-11:05)
> Licensed under GNU GPL v2
> For bug reports, read
>         http://openocd.org/doc/doxygen/bugs.html
> debug_level: 2
> 
> Info : auto-selecting first available session transport "swd". To override use 'transport select <transport>'.
> Error: unable to find CMSIS-DAP device

Could you please give me some advice what I should do?

Thank you,

**Comment by joric** [comment]
I've been told openocd just works without unlocking. Haven't really tried. The command was openocd -f interface/stlink.cfg -f target/nrf52.cfg -c "gdb_flash_program enable" -c "gdb_breakpoint_override hard" -c "init" -c "reset halt" -c "flash write_image erase ./adafruitnrf52.hex" hope that helps.
