### ISSUE TITLE
Help with debuging.

### ISSUE THREAD

**Issue by ilukinov** [joric/nrfmicro#25]
He, Joric,
Thanks for puttign so much time into this project.
I'm building my own keyboard and wanted to try this nrf52 qmk  firmware on a dongle before I order pcb's.  

I have [this](https://www.nordicsemi.com/Software-and-tools/Development-Kits/nRF52840-Dongle) dongle from Nordic and can't figure out how to make it work with nrf52 qmk firmware, can you help me on how do I debug this firmware. 

**What I already managed to do:**
1. Unlocked and flashed bootloader (pca10056_bootloader-0.2.11_s140_6.1.1.hex)
2. Confirmed that I can upload uf2 firmware via usb (tried circuitpython, blinked led on a board)
3. Tried to flash your [modified](https://github.com/ilukinov/qmk/tree/nrf52-jorne/keyboards/keyt_ble)(changed pins to mine) jorne firmware(master half), but nothing happens, no new usb device appears, no keys send, no debug port, no bluetooth device. 

Can you please take a look at my code and, maybe you will spot some obviuos thing that I did wrong or need to change? 

Thanks

**Comment by joric** [comment]
I can't help really, I just can't. Maybe there is a boot loop or something, maybe keys are always pressed because pins are soldered to LEDs instead of input, I don't know really.
