### ISSUE TITLE
Cheaper USB-C connector 

### ISSUE THREAD

**Issue by BenRoe** [joric/nrfmicro#3]
Hi,
i followed you project for a while. Right now i collect all the parts.
I already have the pcb's. 
I found a cheaper alternative to [your connector](https://lcsc.com/product-detail/USB-Type-C_MC-311D_C136423.html) in the part list.
https://lcsc.com/product-detail/USB-Type-C_Korean-Hroparts-Elec-TYPE-C-31-M-12_C165948.html
I have these connectors here and they fit on the pcb. Connectors too.

**Comment by joric** [comment]
I DID point LCSC part to C136423, read my BOM more carefully. Closing.
