### ISSUE TITLE
E73 on the other side on rev1.3

### ISSUE THREAD

**Issue by enikesha** [joric/nrfmicro#31]
Am I getting this right that E73 has moved onto other side of pcb on rev1.3? If that's the case, what is the best way to use it on jorne? Should it be socketed same way as ProMicro, bottom side up with E73 between pcbs? I'm not sure the LiPo will fit with the shield in place. 
Or it could be possible to use other column for sockets? Not sure that TRRS could be used as is. And OLED jumper-pads should be soldered on the backside?

**Comment by joric** [comment]
Yes it's supposed to be flipped antenna down. It's also 2x thinner. Allows oled screens to be at the same height as with pro micro. It's a DROP IN pro micro replacement so please do not modify the host keyboard in any way.
