### ISSUE TITLE
U2 capacitor to ground

### ISSUE THREAD

**Issue by pseudobacon** [joric/nrfmicro#35]
Hi in the release notes for 1.4 it says that a capacitor was added between the 3v3 regulator and ground. 
![image](https://user-images.githubusercontent.com/12183854/97107437-a5e90600-171b-11eb-82e3-44ab03bd8fb6.png) 

But this seems to be missing from the schematic, as well as the PCB, as well as the BOM? I only noticed because I got 1.3 printed, and shortly after the boards arrived at my forwarding warehouse 1.4 was released haha.

**Comment by joric** [comment]
There's no space for capacitor it's been replaced with XTAL. I'll fix the documentation.
