### ISSUE TITLE
Computer not detecting nrfMicro 1.1 over USB, after I was able to flash bootloader using blackmagic and bluepill

### ISSUE THREAD

**Issue by harshitgoel96** [joric/nrfmicro#37]
hi. i was able to flash the nrf micro using bluepill. there was warning, but no error. after flashing when i connect the micro to pc using micro usb, it is not getting detected by the pc. nor there is any led activity on the board.

**Comment by harshitgoel96** [comment]
I am getting Vcc reading of around 3v over usb, so vcc, and GND are connected properly. could it be issue with data line under pads?

**Comment by joric** [comment]
Check soldering or something. I don't have an universal solution for that. Check usb connector (it often gets shorted), and USB data (it's on the outer pads).

**Comment by YHRen** [comment]
@harshitgoel96 can you direct me to how to flash the nrf? I have v1.1 soldered, but not sure how to flash it. Thank you.

**Comment by joric** [comment]
@YHRen what the hell man. Did you miss the entire wiki https://github.com/joric/nrfmicro/wiki/Bootloader
