### ISSUE TITLE
Capacitors for XTAL

### ISSUE THREAD

**Issue by PJE66** [joric/nrfmicro#4]
Love, Love, Love, Love the project - I'm going to borrow some of the design to integrate into my one hand keyboard which currently uses an ATSAMD21.

Just wondering whether there needs to be two small capacitors (22pF) added to the XTAL to match what Adafruit did.

**Comment by joric** [comment]
@PJE66 I was under impression you can skip them and solder the 2-leg resonator (NOT oscillator, oscillator is an active thing with 3-4 legs). They are for the slight frequency correction at inrush and low current. I'm not using external resonator at all, but sometimes it needed if you can't recompile the firmware to use internal RC.  See https://devzone.nordicsemi.com/f/nordic-q-a/40627/zigbee-coordinator-production-configuration-missing-or-invalid/158061#158061 It works if you solder it directly without those load capacitors.

![](https://i.imgur.com/pX2y39k.jpg)

![](https://devzone.nordicsemi.com/cfs-file/__key/communityserver-discussions-components-files/4/PB213632.JPG)
