### ISSUE TITLE
[QA] Can I modify the width to 20mm for JLCPCB SMT assembly?

### ISSUE THREAD

**Issue by donus3** [joric/nrfmicro#40]
I just wondering can I add more width to the pcb each side by 1mm? Would It affect to anything? The reason is that JLCPCB has a choice to let them do SMT assembly. But the min required size is 20 x 20. while the v1.4 size is 18 x 34.

Thank you

**Comment by King-Icewind** [comment]
That will be fine.

**Comment by joric** [comment]
yea or just add a couple of ears as in https://github.com/joric/nrfmicro/wiki/PCBA. you didn't read wiki did you
