### ISSUE TITLE
QMK Firmware creation with MSYS Error

### ISSUE THREAD

**Issue by Tobiassss** [joric/nrfmicro#42]
I'm trying to build QMK Firmware for my NRFMicro.
Installing MSYS and running "qmk setup" worked fine. And compiling Firmware for the standard branch ( qmk/qmk_firmware Branch: master ) works also.
But using the Fork for NRFMicro ( sekigon-gonnoc/qmk_firmware  Branch: nrf52) is not possible.
Trying to change to this folder with:
`qmk setup -H /c/Users/Tobias/qmk_firmware-nrf52`
results in an Error:
`Path 'C:/Users/Tobias/qmk_firmware-nrf52' exists but is not a qmk_firmware clone!`

Running `qmk/util/msys2_install.sh` like descibed in the WiKi dosn't help either.

What needs to be changed/added, to get this working?

**Comment by joric** [comment]
Don't do qmk setup it's incompatible with the branch. All commands you need to run are in this article https://github.com/joric/nrfmicro/wiki/QMK
