### ISSUE TITLE
Poor connection between halves

### ISSUE THREAD

**Issue by wizar** [joric/nrfmicro#43]
Hi, I've assembled nrfmicro 1.4 and everything works fine if halves are close to each other. But if there is some obstacle between them right halve starts to loose signal, missing keys, etc. I tried to set `CONFIG_BT_CTLR_TX_PWR_PLUS_8=y` in the configuration, but it doesn't really help. FWIW I'm using [this module](https://aliexpress.ru/item/1005001679109676.html?spm=a2g39.orderlist.0.0.82dc4aa68JmsyX&_ga=2.229786452.950306215.1627474686-937825319.1577991857).

I also tried to assemble new one, but it didn't make any difference - slave is always having connection issues, while master (left) is working just great. Do you have any idea what could be wrong?

**Comment by joric** [comment]
Not sure why it loses signal. Halves are usually too close to affect the signal somehow. Try different firmware, i.e QMK/ZMK/Bluemicro, I heard they behave differently.
