### ISSUE TITLE
nrfMicro1.4 crystal not need capacitors ?

### ISSUE THREAD

**Issue by Czzr** [joric/nrfmicro#45]
hi i saw a crystal in Nordic's schematic.  But no capacitor is connect in nrfMicro1.4. Maybe it's oscillators(It come in 4 pins packages and contain the electronic required to oscillate) ?
![批注 2021-08-26 183326](https://user-images.githubusercontent.com/65123619/130949222-4939482b-fa11-4115-97a7-faad9e687b1f.jpg)

**Comment by Koxx3** [comment]
hello, sorry but I have the same question and the link is broken. I also don't understand why there is no caps for the crystal ;)

**Comment by joric** [comment]
It's https://github.com/joric/nrfmicro/wiki/Components#crystal now. It just works.

**Comment by Koxx3** [comment]
Ok. Thanks a lot !
