### ISSUE TITLE
There was an error while building the Corne ble firmware. Here is the error message.

### ISSUE THREAD

**Issue by 624245305** [joric/nrfmicro#5]
Root@DESKTOP-GD3O2BA:/mnt/c/qmk_firmware-nrf52-jorne# make jorne_ble/master
Making jorne_ble/master with keymap default

"PLATFORM NRF5"
Compiling: /mnt/c/SDK/nRF5_SDK_15.0.0_a53641a/components/libraries/crc16/crc16.c /mnt/c/SDK/nRF5_SDK_15.0.0_a53641a/components/libraries/crc16/crc16.c: In function 'crc16_compute' :
/mnt/c/SDK/nRF5_SDK_15.0.0_a53641a/components/libraries/crc16/crc16.c:50:5: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
     For (uint32_t i = 0; i < size; i++)
     ^
/mnt/c/SDK/nRF5_SDK_15.0.0_a53641a/components/libraries/crc16/crc16.c:50:5: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to Compile your code
Tmk_core/nrf.mk:953: recipe for target '.build/libnrf.sdk15.NRF52840.a//mnt/c/SDK/nRF5_SDK_15.0.0_a53641a/components/libraries/crc16/crc16.o' failed
Make[1]: *** [.build/libnrf.sdk15.NRF52840.a//mnt/c/SDK/nRF5_SDK_15.0.0_a53641a/components/libraries/crc16/crc16.o] Error 1
Make finished with errors
Makefile: 529: recipe for target 'jorne_ble/master' failed
Make: *** [jorne_ble/master] Error 1

Build jian ble and ergo42 ble before, jorne ble is a newly built repository, also in accordance with jian ble

**Comment by joric** [comment]
Please always read before posting https://github.com/joric/nrfmicro/wiki/Software#building-keyboard-firmware
