### ISSUE TITLE
Can ST-LINK/V2 be replaced by CMSIS-DAP?

### ISSUE THREAD

**Issue by yejianfengblue** [joric/nrfmicro#52]
The [doc](https://github.com/joric/nrfmicro/wiki/Bootloader#st-linkv2) says ST-LINK/V2 needs a CMSIS-DAP patch. And then I searched CMSIS-DAP and found [CMSIS DAP/DAPLink Emulator Simulator](https://www.aliexpress.com/wholesale?SearchText=cmsis+dap), whose price is just $0.5 more expensive than ST-LINK/V2.

Can it be used to unlock and flash the bootloader with the same openocd commands? If yes, it's the most friendly to non-hardware developer user, because no additional firmware flash or patch is required and the price is almost the same.

unlock
`openocd -d2 -f interface/cmsis-dap.cfg -f target/nrf52.cfg -c "nrf52.dap apreg 1 0x04 0x01"`

flash
`openocd -f interface/stlink.cfg -f target/nrf52.cfg -c "gdb_flash_program enable" -c "gdb_breakpoint_override hard" -c "init" -c "reset halt" -c "flash write_image erase ./bootloader.hex`

**Comment by joric** [comment]
I don't know.
