### ISSUE TITLE
zephyr support

### ISSUE THREAD

**Issue by ntn888** [joric/nrfmicro#56]
this is an excellent project! finally an affordable lowpower IOT board. (i believe it's 30usd/5bunch on PCBway fully assembled)

are there any plans of getting this board upstream on zephyr rtos? i believe this would make it to the next level! also bring up some exposure...

**Comment by joric** [comment]
There's no Zephyr but there's ZMK (use nRFMicro 1.3 define). I don't think it can be mass produced (pads are too small and courtyards are too close), it's a DIY board, handsoldering only.

**Comment by ntn888** [comment]
i see. thanks for the attention!
