### ISSUE TITLE
Any plan on embedding the nrf52840 directly on the board?

### ISSUE THREAD

**Issue by Miigon** [joric/nrfmicro#58]
It seems like JLCPCB now has NRF52840-QIAA-R in stock. If we embed the nrf52840 directly on the board, the whole board can be assembled using JPCPCB SMT soldering service, with no hand-soldering required.
It's also probably cheaper to do it this way since we don't have to purchase the components separately

**Comment by joric** [comment]
https://github.com/joric/nrfmicro/wiki/PCBA
