### ISSUE TITLE
Black magic probe does not show up in COM ports

### ISSUE THREAD

**Issue by JiaGengChang** [joric/nrfmicro#59]
Hi Joric,

I flashed black magic firmware into bluepill using ST-LINK V2 as the UART-to-USB method did not work for me (maybe because of the BOOT0 resistor issue you linked).

Now, black magic ports show up under "libusb-win32 devices" on windows 10 device manager, instead of showing up under Ports (COM & LPT).

![device-manager-screen](https://user-images.githubusercontent.com/41614353/170417826-4c2bb9be-5a33-4174-b098-9fb58401840a.png)

I suspect it is because of this reason that the remaining instructions to unlock and flash do not work (error is that COM5 is not recognized).

The Ports (COM & LPT) dropdown only appears when I click "View -> Show hidden devices", and it is the following 
![device-manager-ports-section](https://user-images.githubusercontent.com/41614353/170418141-7ba889b8-2450-4c37-a784-b8662e411e07.png)

In this case, is there a way to locate this Black Magic GDB Server?

**Comment by JiaGengChang** [comment]
Hi Joric,

As an update, I have also managed to flash black magic firmware into bluepill using UART and the official demonstrator GUI from STM. 

However, the issue that the black magic probe does not show up under Ports (COM and LPT) in Device Manager persists. It still shows up under "libusb-win32 devices", and so I do not know what its address.

**Comment by JiaGengChang** [comment]
I managed to solve this problem. 

First, my version of zadig (2.0) was not the latest version (version 2.7). So I switched to that. 

Using zadig 2.7, I upgraded/downgraded both Black Magic GDB Server and Black Magic UART port to "USB Serial (CDC)". 

![zadig-1](https://user-images.githubusercontent.com/41614353/170437249-0d929945-2b23-41ac-995d-3f6a237311d8.png)

Two COM ports instantly appeared in windows 10 Device Manager. 

![device-manager-solved](https://user-images.githubusercontent.com/41614353/170437532-ddee5bcd-e4e7-4f5f-84bd-5a5cf33a26a2.png)

Selecting anything other than "USB Serial (CDC)", including the "libusb-win32" that is recommended in the wiki bootloader section, prevents the ports from being shown in device manager.

**Comment by Timception** [comment]
I managed to get to the same place you did. After that, I cannot get the bluepill blackmagic to flash the nrfmicro. Been trying for weeks. Im not a pro and the explanation and clip are too funny and skip so many things for noobs like me. I bought j-link, st-link, everything. None work after following the documentation. Help needed badly.

**Comment by Sweet-tooth-man** [comment]
> Мне удалось добраться до того же места, что и вы. После этого я не могу заставить bluepill blackmagic прошить nrfmicro. Пытался неделями. Я не профессионал, и объяснение и клип слишком забавны и пропускают так много вещей для нубов, таких как я. Я купил j-link, st-link, все. Ни один из них не работает после выполнения документации. Помощь нужна очень.

did you manage to solve the problem?
