### ISSUE TITLE
Need help!: problem flashing the bootloader 

### ISSUE THREAD

**Issue by lebbtheoriginal** [joric/nrfmicro#60]
Hi, first of all thanks for the work you put in. But i have met a problem that i can't seem to solve:

board nrfMicro 1.4
When i tried flashing the chip with a bluepill flashed with bmp they output this error:

Target voltage: ABSENT!
Exception: SWDP invalid ACK
SW-DP scan failed!
Attaching to Remote target failed
Target does not support this command.

i thought that i solder something wrong, after a few weeks of frustrations and google searching, even hooking up a pull up resistor doesn't seems to fix the problem, even ordering another bluepill to test output the same error, and when i tried an st-link flash with cmis-dap patch they output this:

Open On-Chip Debugger 0.11.0
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
debug_level: 2

swd
Warn : Using CMSIS-DAPv2 interface 1 with wrong class 10 subclass 0 or protocol 0
Info : Using CMSIS-DAPv2 interface with VID:PID=0xc251:0xf001, serial=0001A0000000
Warn : could not claim interface: Resource busy
Error: error writing data: Input/Output Error
Error: CMSIS-DAP command CMD_INFO failed.

the kernel log:
[ 5017.882236] usb 1-7.4: Product: CMSIS-DAP
[ 5017.882237] usb 1-7.4: Manufacturer: X893 ARM
[ 5017.882239] usb 1-7.4: SerialNumber: 0001A0000000
[ 5017.907217] cdc_acm 1-7.4:1.0: ttyACM0: USB ACM device
[ 5017.907894] hid-generic 0003:C251:F001.0013: hiddev3,hidraw7: USB HID v1.00 Device [X893 ARM CMSIS-DAP] on usb-0000:02:00.0-7.4/input2
[ 5254.884960] usb 1-7.4: usbfs: process 13627 (openocd) did not claim interface 1 before use
[ 5307.286692] usb 1-7.4: usbfs: process 13957 (openocd) did not claim interface 1 before use

this seems like openocd cant claims the interfaces for cmisdap,is theres anyway else to flashing the nrfMicro? i might even try the j-link but i dont think it will be better

**Comment by joric** [comment]
I don't know really =( try flashing a standalone module maybe it's soldering.
