### ISSUE TITLE
Unrecognized Device Blue Pill to Blackmagic

### ISSUE THREAD

**Issue by drakumus** [joric/nrfmicro#61]
Followed instructions to download blackmagic to blue pill:

- Hook up an UART adapter to Bluepill (A9 - RX pin, A10 - TX pin).
- Set Bluepill jumpers to the bootloader mode (BOOT0 jumper=1, BOOT1 jumper=0).
- Plug in UART adapter to the computer. Run "STM32 Flash loader demonstrator".
- Download to device blackmagic_dfu.bin at offset 0x8000000 with "Global Erase" option. < verified
- Download to device blackmagic.bin at offset 0x8002000 with "Erase necessary pages" option. < verified
- Put Bluepill jumpers back to the operational mode (BOOT0 jumper=0, BOOT1 jumper=0).
- Using Zadig after that to attempt to install libusb-win32 fails. < FAILS

When plugging back in the Bluepill windows no longer recognizes the device.
![image](https://user-images.githubusercontent.com/9385708/186815368-7956ddd6-78d3-4669-aa75-e8ffe1c7a010.png)
Attempting to install libusb-win32 drivers to the device with zadig fails as well.
![image](https://user-images.githubusercontent.com/9385708/186816226-a862926c-f4f1-4a14-badd-4bdde9498fbb.png)
This happened on 2 blue-pills.

Plugging in the blue-pills before attempting this process showed up on windows as STM32X device and the fact that UART was successful tells me it's unlikely the Dataline resistor is at fault here. Not sure what to do at this point

**Comment by joric** [comment]
Maybe this https://github.com/joric/nrfmicro/wiki/Bootloader#possible-issues

**Comment by drakumus** [comment]
I went through those before posting:
The device can be connected overUART so that rules out the pull up resistor.
Windows doesn't recognize the device at all so the other issue referenced doesn't help me unfortunately. Their device just needed different USB drivers.

My running theory is the dfu flashed at address 0x800000 doesn't work for my board.

**Comment by drakumus** [comment]
I bought another set of bluepills. This set matches the images on the troubleshooting page.
Checked the resistor value and it is the correct 10k.
Connected to the device over UART and realized something:
On both boards, iteration doesn't matter, it only detects 32kb of flash.
It looks like a minimum of 64kb is required for blackmagic probe.

**Comment by drakumus** [comment]
![image](https://user-images.githubusercontent.com/9385708/187132031-8ddd5c21-4731-49fc-ad01-a79b747c6a83.png)
![image](https://user-images.githubusercontent.com/9385708/187132075-0112a347-c44e-4c8b-98c5-99be45981a31.png)
A side by side of the 2 versions of blue pill, left one is the first set I bought, right one is the second set

I just noticed the component that has 32k written on it as well. Checking the aliexpress link you gave the first offering of blue pill on aliexpress also has that 32k:
![image](https://user-images.githubusercontent.com/9385708/187132260-bf7e931c-b83d-4800-af83-e90ccab15055.png)

**Comment by drakumus** [comment]
Ok the issue is clear now.
The blue pills I bought off amazon (both types) use the cheaper STM32F103G6T6A (32kb flash)
The aliexpress blue pills use STM32F103C8T6 (64kb flash)

I guess let this be a warning that there are blue pills with smaller flash.
