### ISSUE TITLE
Why not use the chip internal DCDC regulator?

### ISSUE THREAD

**Issue by cirias** [joric/nrfmicro#62]
Hi Joric,

The current design uses an external LDO for the power supply.
I wonder if it's possible to use the internal DC/DC regulator for converting USB or battery voltage to 3.3V?

That will need an additional 10uh inductor between DCCH and VDD. Is there any specific reason you didn't do that?

![2022-11-23-190443_668x412_scrot](https://user-images.githubusercontent.com/6734547/203532275-7d083f86-1876-48bd-ace5-dd6f0d19f35d.png)

**Comment by joric** [comment]
there's nRFMicro 1.2, see wiki.
