### ISSUE TITLE
Battery drops too fast

### ISSUE THREAD

**Issue by shaohao** [joric/nrfmicro#63]
Hi, 
I socketed 2 nrfmicro v1.4 to a split keyboard, and bonded it to two PC with BLE.
I found it takes half day (about 12 hours) for the battery (central)  to drop from 100% to 26%.
Does it drop too fast? I used the zmk power-profiler demo and it told me that the central side will takes 2weeks and 6days

Here is my configuration:
* nrfmicro v1.4 2pcs for split keyboard
* zmk
* sofle split keyboard v2
* bonded ble profiler: 2
* battery: Left: Li-po 61230 200mAh 3.7V, Right:  Li-po 801280 300mAh 3.7V

**Comment by joric** [comment]
Does it have RGB LEDs? They draw 1mA each when off, you have to disable power pin with CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=y. I don't know otherwise, must be software issue. Schematic leaks 10-55 uA depending on LDO.
