### ISSUE TITLE
Missing capacitors on voltage regulator?

### ISSUE THREAD

**Issue by levpopov** [joric/nrfmicro#64]
AP2112 LDO datasheet[1] specifies 1uF capacitors on VIN and VOUT but these are missing in the nrfmicro schematic. Is this intentional?

[1] https://www.diodes.com/assets/Datasheets/AP2112.pdf

PS thank you for this repo, it's a great resource.

**Comment by joric** [comment]
No space, also we have a bunch on the module, it's in the FAQ. If you have space use 10uF before and 4.7uF after.

**Comment by levpopov** [comment]
Ah, thanks for explaining
