### ISSUE TITLE
Need guidance for JLC assembly: missing BOM & CPL files

### ISSUE THREAD

**Issue by buitrung** [joric/nrfmicro#65]
First, thanks for your work on this awesome project!

I'm planning to order the board from JLC and also get assembled by them, because I may not be able to solder all the tiny parts together.
In the step to upload BOM & CPL .csv files, I don't have them.
From your ibom.html, I can extract the list of parts, but I don't find the positions of each part.

Can you show me how to get the desired files?
Here is an example of .csv files that I have successfully uploaded to JLC to get assembly in the past:
https://github.com/JeremyBois/Ogen/blob/main/PCB/data/production/V1.2/bom.csv
https://github.com/JeremyBois/Ogen/blob/main/PCB/data/production/V1.2/positions.csv

**Comment by joric** [comment]
You probably won't be able to build this automatically. Placeholder tolerances are broken.
