### ISSUE TITLE
SuperMini NRF52840 and 52840nano

### ISSUE THREAD

**Issue by dudicoco** [joric/nrfmicro#69]
Currently, the wiki states the SuperMini NRF52840 and 52840nano as the cheapest most readily available mass produced pro-micro compatible MCUs.
It would be helpful if there was a comparison between the two or if it is stated which one is recommended to get.

Thanks

**Comment by joric** [comment]
Well it's there with all the issues, it should be pretty obvious that Supermini sucks less. https://github.com/joric/nrfmicro/wiki/Alternatives#supermini-nrf52840

**Comment by dudicoco** [comment]
Seems like I missed this part https://github.com/joric/nrfmicro/wiki/Alternatives#supermini-nrf52840:~:text=I%27d%20rather%20prefer%20SuperMini%20NRF52840.

Thanks!
