### ISSUE TITLE
Compatibility with IBM model M

### ISSUE THREAD

**Issue by IronLover64** [joric/nrfmicro#74]
Hi, I want to use your circuit to control an IBM model M keyboard and I need to use all the available 28 GPIOs on the board as 24 will be used to control the keyboard and the other 4 for the indicator lights (num lock, caps lock, scroll lock). Will I run into any issues or make any compromises doing this? I remember reading that you can desolder the P0.00 and P0.01 crystal to use as a free pin, but would doing so essentially disable the bluetooth function? I am also wondering if it's not possible to use the P0.12 pin or any of the low frequency for one of the rows/columns . Thanks for reading.

**Comment by joric** [comment]
Crystal is not needed, all pins are listed in pinout article. At least 28 pins (including xtal pins) should be available.

**Comment by joric** [comment]
@IronLover64 https://github.com/joric/nrfmicro/wiki/Components#crystal
