### ISSUE TITLE
Consider to add more firmware information for alternative boards

### ISSUE THREAD

**Issue by kllp** [joric/nrfmicro#9]
To me it's not clear if the nrf52 branch works for the following boards:
Adafruit Feather nRF52840 Express
Particle.io Xenon
Arduino Nano 33 BLE
STM32WB55

How much work is needed for each of them?
If you know please add a note to the wiki page. Thank you!
https://github.com/joric/nrfmicro/wiki/Alternatives#adafruit-feather-nrf52840-express

**Comment by joric** [comment]
I have no idea really. That would require buying every board in the list.
